# Generated by Django 5.2.5 on 2025-08-17 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PaperTrader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("STOPPED", "Stopped"), ("RUNNING", "Running")],
                        default="STOPPED",
                        max_length=10,
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True, editable=False, max_length=255, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrainingJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num_episodes", models.IntegerField(default=200)),
                ("target_equity", models.FloatField(default=200000.0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("STOPPED", "Stopped"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("progress", models.IntegerField(default=0)),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True, editable=False, max_length=255, null=True
                    ),
                ),
            ],
        ),
    ]
