# Generated by Django 5.2.5 on 2025-08-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("control_panel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingjob",
            name="training_mode",
            field=models.CharField(
                choices=[
                    ("EPISODES", "Train for N Episodes"),
                    ("TARGET", "Train to Target Equity"),
                ],
                default="EPISODES",
                max_length=10,
            ),
        ),
    ]
