# Generated by Django 5.2.5 on 2025-08-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("control_panel", "0002_trainingjob_training_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingjob",
            name="initial_cash",
            field=models.FloatField(
                default=100000.0, help_text="The starting principal for the simulation."
            ),
        ),
    ]
