# Generated by Django 5.2.5 on 2025-08-17 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("control_panel", "0003_trainingjob_initial_cash"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetaTrainingJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("best_strategy_details", models.JSONField(blank=True, null=True)),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True, editable=False, max_length=255, null=True
                    ),
                ),
            ],
        ),
    ]
