# Generated by Django 5.2.5 on 2025-08-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("control_panel", "0004_metatrainingjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="papertrader",
            name="model_file",
            field=models.CharField(
                blank=True,
                help_text="e.g., ppo_agent_advanced.pth",
                max_length=255,
                null=True,
            ),
        ),
    ]
