# Generated by Django 5.2.5 on 2025-08-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("control_panel", "0005_papertrader_model_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvaluationJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_file", models.CharField(max_length=255)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True, editable=False, max_length=255, null=True
                    ),
                ),
                ("results", models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
