# Generated by Django 5.2.5 on 2025-08-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "control_panel",
            "0007_rename_best_strategy_details_metatrainingjob_results_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingjob",
            name="best_reward",
            field=models.FloatField(default=0.0),
        ),
    ]
