# Generated by Django 5.2.5 on 2025-08-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("control_panel", "0008_trainingjob_best_reward"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "singleton_id",
                    models.IntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "display_currency",
                    models.CharField(
                        choices=[("USD", "USD ($)"), ("INR", "INR (₹)")],
                        default="USD",
                        max_length=3,
                    ),
                ),
            ],
        ),
    ]
