# Generated by Django 5.2.5 on 2025-08-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("control_panel", "0009_systemsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="metatrainingjob",
            name="progress",
            field=models.IntegerField(default=0),
        ),
    ]
