# Generated by Django 5.2.5 on 2025-08-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("control_panel", "0010_metatrainingjob_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluationjob",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="metatrainingjob",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="papertrader",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trainingjob",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
