# Generated by Django 5.2.5 on 2025-08-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("control_panel", "0011_evaluationjob_error_message_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="papertrader",
            name="error_message",
        ),
        migrations.AlterField(
            model_name="papertrader",
            name="model_file",
            field=models.CharField(
                blank=True, help_text="e.g., best_agent.pth", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="papertrader",
            name="status",
            field=models.CharField(
                choices=[
                    ("STOPPED", "Stopped"),
                    ("RUNNING", "Running"),
                    ("FAILED", "Failed"),
                ],
                default="STOPPED",
                max_length=10,
            ),
        ),
    ]
