# Generated by Django 6.0.3 on 2026-04-03 23:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0012_remove_papertrader_error_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingjob',
            name='num_episodes',
        ),
        migrations.RemoveField(
            model_name='trainingjob',
            name='target_equity',
        ),
        migrations.RemoveField(
            model_name='trainingjob',
            name='training_mode',
        ),
        migrations.AddField(
            model_name='papertrader',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='papertrader',
            name='initial_cash',
            field=models.DecimalField(decimal_places=2, default=100000.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='trainingjob',
            name='feature_set_key',
            field=models.CharField(default='all_in', max_length=50),
        ),
        migrations.AddField(
            model_name='trainingjob',
            name='hyperparameter_key',
            field=models.CharField(default='balanced', max_length=50),
        ),
        migrations.AddField(
            model_name='trainingjob',
            name='window_size',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='trainingjob',
            name='initial_cash',
            field=models.FloatField(default=100000.0),
        ),
        migrations.CreateModel(
            name='TradeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.CharField(max_length=10)),
                ('action', models.CharField(max_length=4)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=15)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('notional_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='control_panel.papertrader')),
            ],
        ),
    ]
