# Generated by Django 5.2.10 on 2026-04-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0014_trainingjob_name_model_weights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papertrader',
            name='status',
            field=models.CharField(choices=[('STOPPED', 'Stopped'), ('RUNNING', 'Running'), ('PAUSED', 'Paused'), ('FAILED', 'Failed')], default='STOPPED', max_length=10),
        ),
    ]
