# Generated by Django 5.2.10 on 2026-04-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0016_tradingreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='papertrader',
            name='goal_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='papertrader',
            name='high_water_mark',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='papertrader',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
    ]
