# Generated by Django 5.2.10 on 2026-04-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0017_papertrader_goal_amount_papertrader_high_water_mark_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TradingReport',
        ),
        migrations.AddField(
            model_name='papertrader',
            name='stop_loss_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
