# Generated by Django 5.2.10 on 2026-04-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0018_delete_tradingreport_papertrader_stop_loss_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('DAILY', 'Daily Summary'), ('WEEKLY', 'Weekly Rolling Analysis'), ('MONTHLY', 'Monthly Performance')], max_length=15)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('markdown_path', models.CharField(max_length=255)),
                ('pdf_path', models.CharField(blank=True, max_length=255, null=True)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_trades', models.IntegerField(default=0)),
                ('win_rate', models.FloatField(default=0.0)),
            ],
        ),
    ]
