# Generated by Django 5.2.10 on 2026-04-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0019_tradingreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='notify_ab_test',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='notify_eod',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='notify_sos',
            field=models.BooleanField(default=True),
        ),
    ]
