# Generated by Django 5.2.10 on 2026-04-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0020_systemsettings_notify_ab_test_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('action_type', models.CharField(blank=True, max_length=50, null=True)),
                ('target_live_id', models.IntegerField(blank=True, null=True)),
                ('target_paper_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
