# Generated by Django 5.2.10 on 2026-04-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0021_systemalert'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemAlert',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='notify_ab_test',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='notify_eod',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='notify_sos',
        ),
        migrations.AddField(
            model_name='trainingjob',
            name='is_live_trading_ready',
            field=models.BooleanField(default=False, help_text='Checked after successful evaluation'),
        ),
    ]
