# Generated by Django 5.2.10 on 2026-04-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0022_delete_systemalert_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical Level'), ('AB_SWAP', 'A/B Test Swap Request')], default='INFO', max_length=15)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('insist_count', models.IntegerField(default=0)),
                ('related_model_reference', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
