# Generated by Django 5.2.10 on 2026-04-10 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0024_systemsettings_notify_ab_test_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Main Alpaca Account'", max_length=100)),
                ('api_key', models.CharField(max_length=255)),
                ('secret_key', models.CharField(max_length=255)),
                ('base_url', models.CharField(default='https://paper-api.alpaca.markets', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='papertrader',
            name='live_net_profit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='papertrader',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='control_panel.brokeraccount'),
        ),
    ]
