# Generated by Django 5.2.10 on 2026-04-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0025_brokeraccount_papertrader_live_net_profit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokeraccount',
            name='is_live',
            field=models.BooleanField(default=False, help_text='Distinguish real-money accounts from Sandbox'),
        ),
    ]
