# Generated by Django 5.2.10 on 2026-04-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0026_brokeraccount_is_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradelog',
            name='sentiment_score',
            field=models.FloatField(default=0.0, help_text='FinBERT Sentiment Score at time of trade'),
        ),
    ]
