# Generated by Django 5.2.10 on 2026-04-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0027_tradelog_sentiment_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradelog',
            name='sentiment_score',
            field=models.FloatField(blank=True, default=0.0, help_text='FinBERT Sentiment Score at time of trade', null=True),
        ),
    ]
