# Generated by Django 5.2.10 on 2026-04-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0028_alter_tradelog_sentiment_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='notify_start_stop',
            field=models.BooleanField(default=False),
        ),
    ]
