# Generated by Django 5.2.14 on 2026-05-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0029_systemsettings_notify_start_stop'),
    ]

    operations = [
        migrations.AddField(
            model_name='metatrainingjob',
            name='ticker',
            field=models.CharField(default='SPY', max_length=20),
        ),
        migrations.AddField(
            model_name='trainingjob',
            name='ticker',
            field=models.CharField(default='SPY', max_length=20),
        ),
    ]
