# Generated by Django 5.2.14 on 2026-05-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0030_metatrainingjob_ticker_trainingjob_ticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='idle_lock_minutes',
            field=models.IntegerField(default=5, help_text='Minutes of inactivity before showing lockscreen (0 to disable)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='idle_logout_minutes',
            field=models.IntegerField(default=30, help_text='Minutes of inactivity before forcefully ending session'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='lockscreen_password',
            field=models.CharField(blank=True, help_text='Hashed PIN or Password for lockscreen', max_length=128, null=True),
        ),
    ]
