# Generated by Django 5.2.14 on 2026-05-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0031_systemsettings_idle_lock_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingjob',
            name='training_duration_days',
            field=models.IntegerField(default=365),
        ),
    ]
