# Generated by Django 5.2.14 on 2026-05-18 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0032_trainingjob_training_duration_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='metatrainingjob',
            name='training_duration_days',
            field=models.IntegerField(default=365),
        ),
    ]
