# Generated by Django 5.2.14 on 2026-05-21 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0033_metatrainingjob_training_duration_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemalert',
            name='level',
            field=models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical Level'), ('EVOLUTION', 'Neural Evolution Promotion')], default='INFO', max_length=15),
        ),
        migrations.CreateModel(
            name='ModelVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed Variant', max_length=150)),
                ('status', models.CharField(choices=[('TESTING', 'Testing'), ('PENDING', 'Pending'), ('PROMOTED', 'Promoted'), ('FAILED', 'Failed'), ('QUEUED', 'Queued')], default='TESTING', max_length=10)),
                ('agent_code', models.TextField(help_text='Full ppo_agent.py source code for this variant')),
                ('model_weights', models.BinaryField(blank=True, help_text='Trained .pth weights if applicable', null=True)),
                ('starting_cash', models.DecimalField(decimal_places=2, default=100.0, help_text="Inherited from parent model's balance at fork time", max_digits=15)),
                ('test_start', models.DateTimeField(auto_now_add=True)),
                ('test_duration_days', models.IntegerField(default=14)),
                ('virtual_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('virtual_trades_count', models.IntegerField(default=0)),
                ('virtual_pnl', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('virtual_pnl_pct', models.FloatField(default=0.0, help_text='PnL as percentage of starting_cash')),
                ('sharpe_ratio', models.FloatField(default=0.0)),
                ('max_drawdown_pct', models.FloatField(default=0.0)),
                ('win_rate', models.FloatField(default=0.0)),
                ('mutation_reasoning', models.TextField(blank=True, help_text='AI reasoning for the code changes')),
                ('diff_summary', models.TextField(blank=True, help_text='Unified diff of code changes')),
                ('celery_task_id', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_trader', models.ForeignKey(blank=True, help_text='The live PaperTrader this variant is benchmarked against', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spawned_variants', to='control_panel.papertrader')),
                ('parent_variant', models.ForeignKey(blank=True, help_text='The variant this was mutated from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='control_panel.modelvariant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VirtualTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.CharField(max_length=20)),
                ('action', models.CharField(max_length=4)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=15)),
                ('price', models.DecimalField(decimal_places=4, max_digits=15)),
                ('notional_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('virtual_balance_after', models.DecimalField(decimal_places=2, default=0, help_text='Running balance after this trade', max_digits=15)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_trades', to='control_panel.modelvariant')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
