# Generated by Django 5.2.14 on 2026-06-07 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0035_systemsettings_alpaca_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingreport',
            name='run_mode',
            field=models.CharField(choices=[('EVOLUTION', 'Evolution Model'), ('PAPER', 'Paper Trading'), ('LIVE', 'Live Trading')], default='PAPER', max_length=20),
        ),
    ]
