# Generated by Django 5.2.14 on 2026-06-24 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0036_tradingreport_run_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineLearningLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ENTRY', 'Entry Recorded'), ('EXIT', 'Exit Recorded'), ('UPDATE', 'Micro-Update'), ('CHECKPOINT', 'Checkpoint Saved'), ('INIT', 'Learner Initialized'), ('MANUAL', 'Manual Edit')], max_length=15)),
                ('symbol', models.CharField(blank=True, max_length=20)),
                ('details', models.JSONField(default=dict)),
                ('reason', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('trader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='control_panel.papertrader')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
