# Generated by Django 5.2.14 on 2026-06-26 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0037_onlinelearninglog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('steam_app_id', models.CharField(blank=True, help_text='Steam App ID if it is a Steam game', max_length=50, null=True)),
                ('local_path', models.CharField(blank=True, help_text='Path to local executable for non-Steam games', max_length=500, null=True)),
                ('hours_played', models.FloatField(default=0.0)),
                ('cover_image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('animated_bg_url', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='onlinelearninglog',
            name='event_type',
            field=models.CharField(choices=[('ENTRY', 'Entry Recorded'), ('EXIT', 'Exit Recorded'), ('UPDATE', 'Micro-Update'), ('CHECKPOINT', 'Checkpoint Saved'), ('INIT', 'Learner Initialized'), ('MANUAL', 'Manual Edit'), ('DECISION', 'Model Decision Check')], max_length=15),
        ),
        migrations.CreateModel(
            name='GameGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('content_markdown', models.TextField(help_text='Extracted guide content styled in markdown')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guides', to='control_panel.game')),
            ],
        ),
        migrations.CreateModel(
            name='GameVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('youtube_url', models.URLField()),
                ('video_id', models.CharField(blank=True, help_text='Extracted YouTube Video ID', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='control_panel.game')),
            ],
        ),
    ]
