# Generated by Django 5.2.14 on 2026-06-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0038_game_alter_onlinelearninglog_event_type_gameguide_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='gaming_rig_ip',
            field=models.CharField(blank=True, default='', help_text='Local IP or hostname of the Windows gaming machine', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='gaming_rig_ssh_password',
            field=models.CharField(blank=True, default='', help_text='Windows user password or SSH key path', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='gaming_rig_ssh_username',
            field=models.CharField(blank=True, default='', help_text='Windows user account name for SSH connection', max_length=255),
        ),
    ]
