# Generated by Django 5.2.14 on 2026-06-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0039_systemsettings_gaming_rig_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='steam_username',
            field=models.CharField(blank=True, default='', help_text='Steam ID64 or custom profile URL name for auto-syncing library playtimes', max_length=255),
        ),
    ]
