# Generated by Django 5.2.14 on 2026-06-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0040_systemsettings_steam_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='steam_api_key',
            field=models.CharField(blank=True, default='', help_text='Steam Web API Key for reliable full library sync', max_length=255),
        ),
    ]
