# Generated by Django 5.2.14 on 2026-06-30 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0041_systemsettings_steam_api_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetWatchlistGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('steam_app_id', models.CharField(blank=True, max_length=50, null=True)),
                ('target_budget', models.FloatField(default=30.0)),
                ('check_steam', models.BooleanField(default=True)),
                ('check_epic', models.BooleanField(default=True)),
                ('check_xbox', models.BooleanField(default=True)),
                ('current_price', models.FloatField(blank=True, null=True)),
                ('lowest_platform', models.CharField(blank=True, max_length=50, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('notified_under_budget', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WatchlistGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('expected_release_date', models.CharField(blank=True, max_length=100, null=True)),
                ('business_model', models.CharField(choices=[('F2P', 'Free to Play'), ('P2P', 'Pay to Play'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=50)),
                ('price_estimate', models.CharField(blank=True, max_length=50, null=True)),
                ('system_requirements', models.TextField(blank=True, null=True)),
                ('official_website', models.URLField(blank=True, null=True)),
                ('current_status', models.CharField(blank=True, max_length=100, null=True)),
                ('check_interval_days', models.IntegerField(default=7)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='playtime_offset',
            field=models.FloatField(default=0.0, help_text='Manual playtime offset to add to Steam hours'),
        ),
        migrations.CreateModel(
            name='GameBetaInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('signup_link', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('notified', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beta_infos', to='control_panel.game')),
            ],
        ),
        migrations.CreateModel(
            name='GamePlaytimeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('limit_minutes', models.IntegerField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='control_panel.game')),
            ],
        ),
    ]
