# Generated by Django 5.2.14 on 2026-06-30 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0041_systemsettings_steam_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='logo_url',
            field=models.CharField(blank=True, help_text='Transparent logo SVG/PNG URL for overlay', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='process_name',
            field=models.CharField(blank=True, default='', help_text='Windows executable name to track playtime (e.g. ForzaHorizon5.exe)', max_length=255),
        ),
        migrations.CreateModel(
            name='DailyPlaytimeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('hours_played', models.FloatField(default=0.0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='control_panel.game')),
            ],
            options={
                'unique_together': {('game', 'date')},
            },
        ),
    ]
