# Generated by Django 5.2.14 on 2026-06-30 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0042_budgetwatchlistgame_watchlistgame_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamebetainfo',
            name='signup_link',
            field=models.TextField(),
        ),
    ]
