# Generated by Django 5.2.14 on 2026-06-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0042_game_is_favorite_game_logo_url_game_process_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='playtime_offset',
            field=models.FloatField(default=0.0, help_text='Manual playtime offset to add to Steam hours'),
        ),
    ]
