# Generated by Django 5.2.14 on 2026-06-30 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0043_alter_gamebetainfo_signup_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='years_played',
            field=models.FloatField(default=1.0, help_text='Number of years this game has been played to normalize rankings'),
        ),
    ]
