# Generated by Django 5.2.14 on 2026-06-30 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0044_game_years_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='global_wishlist_budget',
            field=models.FloatField(default=1000.0, help_text='Default target budget in INR for discount watchlist games'),
        ),
        migrations.AlterField(
            model_name='budgetwatchlistgame',
            name='current_price',
            field=models.FloatField(blank=True, help_text='Current lowest price in INR (Rupees)', null=True),
        ),
        migrations.AlterField(
            model_name='budgetwatchlistgame',
            name='target_budget',
            field=models.FloatField(default=1000.0, help_text='Target budget in INR (Rupees)'),
        ),
    ]
