# Generated by Django 5.2.14 on 2026-07-01 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0045_systemsettings_global_wishlist_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='watch_beta_recruitment',
            field=models.BooleanField(default=False, help_text='Watch this game for beta recruitment signups'),
        ),
    ]
