# Generated by Django 5.2.14 on 2026-07-01 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0046_game_watch_beta_recruitment'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetwatchlistgame',
            name='buy_link',
            field=models.TextField(blank=True, help_text='Direct link to purchase the deal', null=True),
        ),
    ]
