# Generated by Django 5.2.14 on 2026-07-01 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0047_budgetwatchlistgame_buy_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlistgame',
            name='steam_app_id',
            field=models.CharField(blank=True, help_text='Steam App ID if available', max_length=50, null=True),
        ),
    ]
