# Generated by Django 5.2.14 on 2026-07-01 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0048_watchlistgame_steam_app_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlistgame',
            name='header_image',
            field=models.URLField(blank=True, help_text='Horizontal banner image URL', max_length=500, null=True),
        ),
    ]
