# Generated by Django 5.2.14 on 2026-07-01 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0049_watchlistgame_header_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Note title or Category (e.g. Cheat, Level Key, Crafting Recipe)', max_length=200, null=True)),
                ('content', models.TextField(help_text='Content of the note')),
                ('is_cheat', models.BooleanField(default=False, help_text='If true, displays with a copy button for easy copying during gameplay')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='control_panel.game')),
            ],
        ),
    ]
