# config/config.yaml

# --- Backtesting Configuration ---
backtest:
  start_date: "2023-01-01"
  end_date: "2024-01-01"
  initial_cash: 100000.0
  transaction_cost_pct: 0.001 # 0.1%
  slippage_pct: 0.0005        # 0.05%

# --- Model Configuration ---
model:
  name: "PPO" # or "DQN"
  learning_rate: 0.0003
  gamma: 0.99

# --- Data Configuration ---
data:
  symbol: "SPY"
  timeframe: "1d" # e.g., 1m, 5m, 1h, 1d